var searchData=
[
  ['y_596',['y',['../struct__drivers___1_1__udp__driver___1_1mocap__states.html#ad1cfc5435f2de711e46c9142f39ff855',1,'_drivers_::_udp_driver_::mocap_states']]],
  ['yaw_5fquaternion_5finverse_5foffset_5f_597',['yaw_quaternion_inverse_offset_',['../classVehicleState.html#ae0d760e30dfd39495c6762342194bf6b',1,'VehicleState']]],
  ['yawcomputation_598',['yawComputation',['../piecewise__polynomial__trajectory_8hpp.html#a945bcfe8dadfcf84ddb1a9117670eb22',1,'yawComputation(const Eigen::VectorXd &amp;Vx_coef, const Eigen::VectorXd &amp;Vy_coef, double t):&#160;piecewise_polynomial_trajectory.cpp'],['../piecewise__polynomial__trajectory_8cpp.html#a945bcfe8dadfcf84ddb1a9117670eb22',1,'yawComputation(const Eigen::VectorXd &amp;Vx_coef, const Eigen::VectorXd &amp;Vy_coef, double t):&#160;piecewise_polynomial_trajectory.cpp']]],
  ['yawdotcomputation_599',['yawDotComputation',['../piecewise__polynomial__trajectory_8hpp.html#aef28200ec3c1fb1475dba9887492046f',1,'yawDotComputation(const Eigen::VectorXd &amp;Vx_coef, const Eigen::VectorXd &amp;Vy_coef, const Eigen::VectorXd &amp;Ax_coef, const Eigen::VectorXd &amp;Ay_coef, double t):&#160;piecewise_polynomial_trajectory.cpp'],['../piecewise__polynomial__trajectory_8cpp.html#aef28200ec3c1fb1475dba9887492046f',1,'yawDotComputation(const Eigen::VectorXd &amp;Vx_coef, const Eigen::VectorXd &amp;Vy_coef, const Eigen::VectorXd &amp;Ax_coef, const Eigen::VectorXd &amp;Ay_coef, double t):&#160;piecewise_polynomial_trajectory.cpp']]],
  ['yawdotdotcomputation_600',['yawDotDotComputation',['../piecewise__polynomial__trajectory_8hpp.html#a21eadf420a96cc47cebc437625c325a6',1,'yawDotDotComputation(const Eigen::VectorXd &amp;Vx_coef, const Eigen::VectorXd &amp;Vy_coef, const Eigen::VectorXd &amp;Ax_coef, const Eigen::VectorXd &amp;Ay_coef, const Eigen::VectorXd &amp;Jx_coef, const Eigen::VectorXd &amp;Jy_coef, double t):&#160;piecewise_polynomial_trajectory.cpp'],['../piecewise__polynomial__trajectory_8cpp.html#a21eadf420a96cc47cebc437625c325a6',1,'yawDotDotComputation(const Eigen::VectorXd &amp;Vx_coef, const Eigen::VectorXd &amp;Vy_coef, const Eigen::VectorXd &amp;Ax_coef, const Eigen::VectorXd &amp;Ay_coef, const Eigen::VectorXd &amp;Jx_coef, const Eigen::VectorXd &amp;Jy_coef, double t):&#160;piecewise_polynomial_trajectory.cpp']]],
  ['yawspeed_601',['yawspeed',['../struct__drivers___1_1__udp__driver___1_1mocap__states.html#a6381b0377bdab85a24fcf8c7711380b2',1,'_drivers_::_udp_driver_::mocap_states']]]
];
