name: Deploy Docusaurus Site

on:
  push:
    branches:
      - main  # or the branch where your website source code resides

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18  # specify the Node.js version you're using

      - name: Install dependencies
        working-directory: ./docs  # Change this if necessary
        run: |
          npm ci  # or npm install if package-lock.json is not present

      - name: Build Docusaurus site
        working-directory: ./docs
        run: npm run build

      - name: Check if CNAME exists and create it if missing
      run: |
        if [ ! -f ./docs/build/CNAME ]; then
          echo "acslstack.com" > ./docs/build/CNAME
        fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build  # Change this if necessary
          cname: acslstack.com # Add your custom domain here

